"""
Secure physical storage for invoice/document attachments.

This module owns only physical document bytes.

It intentionally has no SQLite, stock, Product, Batch or audit-event
authority. Metadata persistence belongs to the repository layer.
"""

from __future__ import annotations

import hashlib
import os
import uuid
from datetime import datetime
from pathlib import Path
from typing import Dict


DEFAULT_MAX_BYTES = 10 * 1024 * 1024


class DocumentStorageError(Exception):
    """Raised when a document cannot be safely stored or accessed."""


class InvoiceDocumentStorage:
    """
    Secure filesystem storage for invoice/document attachments.

    Supported formats:
    - PDF
    - JPEG
    - PNG

    The original filename is metadata only.
    Physical filenames are always generated by the system.
    """

    _PDF_SIGNATURE = b"%PDF-"
    _JPEG_SIGNATURE = b"\xff\xd8\xff"
    _PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"

    _FORMAT_BY_EXTENSION = {
        ".pdf": {
            "mime_type": "application/pdf",
            "stored_extension": ".pdf",
        },
        ".jpg": {
            "mime_type": "image/jpeg",
            "stored_extension": ".jpg",
        },
        ".jpeg": {
            "mime_type": "image/jpeg",
            "stored_extension": ".jpg",
        },
        ".png": {
            "mime_type": "image/png",
            "stored_extension": ".png",
        },
    }

    def __init__(
        self,
        *,
        root_path,
        max_bytes: int = DEFAULT_MAX_BYTES,
    ):
        self.root_path = Path(root_path)

        try:
            normalized_max_bytes = int(max_bytes)
        except (TypeError, ValueError) as exc:
            raise DocumentStorageError(
                "max_bytes deve ser um inteiro positivo."
            ) from exc

        if normalized_max_bytes <= 0:
            raise DocumentStorageError(
                "max_bytes deve ser maior que zero."
            )

        self.max_bytes = normalized_max_bytes

    def store(
        self,
        *,
        content: bytes,
        original_filename: str,
        declared_mime_type: str,
    ) -> Dict[str, object]:
        document_bytes = self._normalize_content(
            content
        )

        original_name = str(
            original_filename
            if original_filename is not None
            else ""
        )

        if not original_name:
            raise DocumentStorageError(
                "Nome original do documento é obrigatório."
            )

        declared_mime = str(
            declared_mime_type
            if declared_mime_type is not None
            else ""
        ).strip().lower()

        if not declared_mime:
            raise DocumentStorageError(
                "MIME type declarado é obrigatório."
            )

        byte_size = len(document_bytes)

        if byte_size == 0:
            raise DocumentStorageError(
                "Documento vazio não é permitido."
            )

        if byte_size > self.max_bytes:
            raise DocumentStorageError(
                "Documento excede o limite máximo permitido."
            )

        extension = Path(
            original_name
        ).suffix.lower()

        format_spec = self._FORMAT_BY_EXTENSION.get(
            extension
        )

        if format_spec is None:
            raise DocumentStorageError(
                "Extensão de documento não suportada."
            )

        detected_mime = self._detect_mime_type(
            document_bytes
        )

        if detected_mime is None:
            raise DocumentStorageError(
                "Assinatura física do documento não suportada."
            )

        expected_mime = str(
            format_spec["mime_type"]
        )

        if detected_mime != expected_mime:
            raise DocumentStorageError(
                "Extensão não corresponde ao conteúdo físico."
            )

        if declared_mime != detected_mime:
            raise DocumentStorageError(
                "MIME type declarado não corresponde ao conteúdo físico."
            )

        attachment_id = (
            "DOC-"
            + uuid.uuid4().hex
        )

        stored_extension = str(
            format_spec["stored_extension"]
        )

        stored_filename = (
            attachment_id
            + stored_extension
        )

        now = datetime.now()

        year = f"{now.year:04d}"
        month = f"{now.month:02d}"

        relative_path = Path(
            year,
            month,
            stored_filename,
        )

        destination = (
            self.root_path
            / relative_path
        )

        self._write_atomic(
            destination=destination,
            content=document_bytes,
        )

        return {
            "attachment_id": attachment_id,
            "original_filename": original_name,
            "stored_filename": stored_filename,
            "relative_path": str(relative_path),
            "mime_type": detected_mime,
            "byte_size": byte_size,
            "sha256": hashlib.sha256(
                document_bytes
            ).hexdigest(),
        }

    def resolve(
        self,
        relative_path,
    ) -> Path:
        raw = str(
            relative_path
            if relative_path is not None
            else ""
        ).strip()

        if not raw:
            raise DocumentStorageError(
                "Caminho relativo do documento é obrigatório."
            )

        requested = Path(raw)

        if requested.is_absolute():
            raise DocumentStorageError(
                "Caminho absoluto não é permitido."
            )

        if ".." in requested.parts:
            raise DocumentStorageError(
                "Path traversal não é permitido."
            )

        root = self.root_path.resolve()

        candidate = (
            self.root_path
            / requested
        ).resolve()

        if (
            candidate == root
            or root not in candidate.parents
        ):
            raise DocumentStorageError(
                "Documento fora da raiz de armazenamento."
            )

        return candidate

    def delete(
        self,
        relative_path,
    ) -> None:
        path = self.resolve(
            relative_path
        )

        if not path.exists():
            return

        if not path.is_file():
            raise DocumentStorageError(
                "Caminho gerenciado não representa um arquivo."
            )

        try:
            path.unlink()
        except OSError as exc:
            raise DocumentStorageError(
                "Falha ao remover documento gerenciado."
            ) from exc

    @classmethod
    def _detect_mime_type(
        cls,
        content: bytes,
    ):
        if content.startswith(
            cls._PDF_SIGNATURE
        ):
            return "application/pdf"

        if content.startswith(
            cls._JPEG_SIGNATURE
        ):
            return "image/jpeg"

        if content.startswith(
            cls._PNG_SIGNATURE
        ):
            return "image/png"

        return None

    @staticmethod
    def _normalize_content(
        content,
    ) -> bytes:
        if isinstance(content, bytes):
            return content

        if isinstance(content, bytearray):
            return bytes(content)

        if isinstance(content, memoryview):
            return content.tobytes()

        raise DocumentStorageError(
            "Conteúdo do documento deve ser binário."
        )

    def _write_atomic(
        self,
        *,
        destination: Path,
        content: bytes,
    ) -> None:
        parent = destination.parent

        part_path = destination.with_name(
            destination.name
            + ".part"
        )

        try:
            parent.mkdir(
                parents=True,
                exist_ok=True,
            )

            with part_path.open("wb") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(
                    handle.fileno()
                )

            os.replace(
                part_path,
                destination,
            )

        except Exception as exc:
            try:
                if part_path.exists():
                    part_path.unlink()
            except OSError:
                pass

            try:
                if destination.exists():
                    destination.unlink()
            except OSError:
                pass

            if isinstance(
                exc,
                DocumentStorageError,
            ):
                raise

            raise DocumentStorageError(
                "Falha ao persistir documento de forma atômica."
            ) from exc
